config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :user_sessions
  resources :games

 root 'welcome#index'

  get 'deal' => 'games#deal', :as => :deal

end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :deck
  attr_accessor :face, :suit, :value

  def initialize(face, suit)
    self.face = face
    self.suit = suit
    if face == "ace"
      self.value =  11
    elsif face.to_i > 0
      self.value = face.to_i
    else
      self.value = 10
    end
  end
end

app/models/deck.rb
class Deck < ActiveRecord::Base
  attr_accessor :cards
  has_many :cards

  def initialize(num_decks)
    self.cards = []
    num_decks.times do
      suits = %w[spades hearts diamonds clubs]
      faces = %w[2 3 4 5 6 7 8 9 10 jack queen king ace]

      faces.each do |face|
        suits.each do |suit|
          cards << Card.new(face, suit)
        end
      end
    end
    self.cards.shuffle!
  end
end

app/models/game.rb
class Game < ActiveRecord::Base

  has_one :deck

end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic 
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  # configuration here, see documentation for sub modules of Authlogic::Session
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user_session, :current_user

  private
    def current_user_session
      return @current_user_session if defined?(@current_user_session)
      @current_user_session = UserSession.find
    end

    def current_user
      return @current_user if defined?(@current_user)
      @current_user = current_user_session && current_user_session.user
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def index
    @game = Game.new
    @game.deck = Deck.new
  end

  def deal
    @playerHand = []
    @dealerHand = []
    @
    respond_to do |format|
      format.js{

      }
    end
  end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController


  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      flash[:notice] = "Login successful!"
      redirect_to root_path
    else
      render :action => :new
    end
  end

  def destroy
    current_user_session.destroy
    flash[:notice] = "Logout successful!"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

 def new
   @user = User.new
 end

 def create
   @user = User.new(user_params)
   if @user.save
     flash[:notice] = "Account registered!"
     redirect_to @user
   else
     render :action => :new
   end
 end

 def show
   @user = @current_user
 end

 def edit
   @user = @current_user
 end

 def update
   @user = @current_user # makes our views "cleaner" and more consistent
   if @user.update_attributes(params[:user])
     flash[:notice] = "Account updated!"
     redirect_to @user
   else
     render :action => :edit
   end
 end

 private

 def user_params
   params.require(:user).permit(:username, :password, :password_confirmation)
 end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/games/deal.js.erb
$('#playerHand').append('<div class="card col-xs-3"> Ace </div>');
$('#dealerHand').append('<div class="card col-xs-3"> Ace </div>');
$('#playerHand').append('<div class="card col-xs-3"> Ace </div>');
$('#dealerHand').append('<div class="card col-xs-3"> Ace </div>');

app/views/games/index.html.erb
<div class="container">
  <div id="dealerHand" class="center-block">

  </div>
  <div class="tableMiddle">

  </div>

  <div id="playerHand" class="center-block">

  </div>
  <div class="actionPanel">
    <%= link_to "Deal", deal_path, class:"btn btn-danger", remote: true %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsBlackjack</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="row">
    <% if !current_user_session %>
      <%= link_to "login", new_user_session_path, class:"btn btn-primary" %>
      <%= link_to "New User", new_user_path, class:"btn btn-primary" %>
    <% else %>
      <%= link_to "Logout", user_session_path(current_user_session), method:"delete", class:"btn btn-primary" %>
    <% end %>
  </div>

<%= yield %>

</body>
</html>

app/views/user_sessions/new.html.erb
<div class="container">
  <h1>Login</h1>

  <%= form_for @user_session do |f| %>
    <%= f.label :username %><br />
    <%= f.text_field :username %><br />
    <br />
    <%= f.label :password %><br />
    <%= f.password_field :password %><br />
    <br />
    <%= f.check_box :remember_me %><%= f.label :remember_me %><br />
    <br />
    <%= f.submit "Login" %>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="container">
  <h1>Register</h1>

  <%= form_for @user do |f| %>
    <%= f.label :username %><br />
    <%= f.text_field :username %><br />
    <br />
    <%= f.label :password %><br />
    <%= f.password_field :password %><br />
    <br />
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %><br />
    <%= f.submit "Register", class:"btn-primary btn" %>
  <% end %>
</div>

app/views/users/show.html.erb
<p>
  <b>Login:</b>
  <%= @user.username %>
</p>

app/views/welcome/index.html.erb
<div class="container">
  <%= link_to "Play a game!", games_path, class:"btn btn-danger" %>
</div>